local M = {}

function M.setup()
	if M.loaded then
		return
	end
	M.loaded = true

	local vscode = require("vscode")
	local i18n = require("shared.i18n")
	local map = vim.keymap.set

	map("i", "<Tab>", function()
		vscode.action("editor.action.inlineSuggest.commit")
	end, { desc = i18n.t("accept_inline_suggestion") })

	map("n", "<leader>n", function()
		vscode.action("kilo-code.addToContext")
	end, { desc = i18n.t("inline_generation_kilo") })
	map("n", "<leader>i", function()
		vscode.action("roo-cline.explainCode")
	end, { desc = i18n.t("explain_code_roo") })
	map("n", "<leader>N", function()
		vscode.action("aichat.insertselectionintochat")
	end, { desc = i18n.t("chat_panel") })

	map("n", "<leader> ", function()
		vscode.action("workbench.action.showCommands")
	end, { desc = i18n.t("show_all_commands") })
	map("n", "<leader>,", function()
		vscode.action("workbench.action.openGlobalSettings")
	end, { desc = i18n.t("settings") })
	map("n", "<leader>Q", function()
		vscode.action("workbench.action.closeWindow")
	end, { desc = i18n.t("close_window") })
	map("n", "<leader>q", function()
		vscode.action("workbench.action.closeActiveEditor")
	end, { desc = i18n.t("close_editor") })
	map("n", "<leader>r", function()
		vscode.action("workbench.action.openRecent")
	end, { desc = i18n.t("recent_files") })
	map("n", "<leader>/", function()
		vscode.action("workbench.action.splitEditor")
	end, { desc = i18n.t("split_editor") })

	map("n", "<leader>o", function()
		vscode.action("outline.focus")
	end, { desc = i18n.t("outline") })
	map("n", "<leader>v", function()
		vscode.action("markdown.showPreview")
	end, { desc = i18n.t("view_markdown") })
	map("n", "<leader>G", function()
		vscode.action("workbench.view.scm")
	end, { desc = i18n.t("source_control") })
	map("n", "<leader>p", function()
		vscode.action("workbench.actions.view.problems")
	end, { desc = i18n.t("problems") })
	map("n", "<leader>c", function()
		vscode.action("workbench.action.closeOtherEditors")
	end, { desc = i18n.t("close_others") })
	map("n", "<leader>t", function()
		vscode.action("workbench.action.terminal.openNativeConsole")
	end, { desc = i18n.t("external_terminal") })
	map("n", "<leader>x", function()
		vscode.action("workbench.view.extensions")
	end, { desc = i18n.t("extensions") })

	map("n", "<leader>ff", function()
		vscode.action("workbench.action.quickOpen")
	end, { desc = i18n.t("find_file") })
	map("n", "<leader>fw", function()
		vscode.action("search.action.openEditor")
	end, { desc = i18n.t("new_search_editor") })
	map("n", "<leader>fs", function()
		vscode.action("workbench.view.search")
	end, { desc = i18n.t("search_text") })
	map("n", "<leader>fd", function()
		vscode.action("workbench.action.gotoSymbol")
	end, { desc = i18n.t("document_symbol") })
	map("n", "<leader>fp", function()
		vscode.action("workbench.action.showAllSymbols")
	end, { desc = i18n.t("project_symbol") })

	map("n", "<leader>gs", function()
		vscode.action("workbench.view.scm")
	end, { desc = i18n.t("git_status") })
	map("n", "<leader>gc", function()
		vscode.action("git.commit")
	end, { desc = i18n.t("git_commit") })
	map("n", "<leader>gC", function()
		vscode.action("git.commitSignedOff")
	end, { desc = i18n.t("git_commit_signed") })
	map("n", "<leader>gp", function()
		vscode.action("git.push")
	end, { desc = i18n.t("git_push") })
	map("n", "<leader>gP", function()
		vscode.action("git.pull")
	end, { desc = i18n.t("git_pull") })
	map("n", "<leader>gf", function()
		vscode.action("git.fetch")
	end, { desc = i18n.t("git_fetch") })
	map("n", "<leader>gb", function()
		vscode.action("git.checkout")
	end, { desc = i18n.t("git_checkout") })
	map("n", "<leader>gS", function()
		vscode.action("git.stageAll")
	end, { desc = i18n.t("git_stage_all") })

	map("n", "<leader>O1", function()
		vscode.action("revealFileInOS")
	end, { desc = i18n.t("open_in_system_explorer") })
	map("n", "<leader>O2", function()
		vscode.action("remote-wsl.revealInExplorer")
	end, { desc = i18n.t("open_in_wsl_explorer") })

	map("n", "<leader>[", function()
		vscode.action("editor.foldAll")
	end, { desc = i18n.t("fold_all") })
	map("n", "<leader>]", function()
		vscode.action("editor.unfoldAll")
	end, { desc = i18n.t("unfold_all") })
	map("n", "za", function()
		vscode.action("editor.toggleFold")
	end, { desc = i18n.t("toggle_code_fold") })

	map("n", "<leader>rn", function()
		vscode.action("editor.action.rename")
	end, { desc = i18n.t("rename_symbol") })
	map("n", "<leader>ca", function()
		vscode.action("editor.action.quickFix")
	end, { desc = i18n.t("quick_fix") })
	map("n", "<leader>u", function()
		vscode.action("editor.action.referenceSearch.trigger")
	end, { desc = i18n.t("go_to_references") })
	map("n", "<leader>dj", function()
		vscode.action("editor.action.marker.next")
	end, { desc = i18n.t("next_marker") })
	map("n", "<leader>dk", function()
		vscode.action("editor.action.marker.prev")
	end, { desc = i18n.t("prev_marker") })

	map("n", "<C-/>", function()
		vscode.action("editor.action.commentLine")
	end, { desc = i18n.t("toggle_line_comment") })
	map("v", "<C-/>", function()
		vscode.action("editor.action.commentLine")
	end, { desc = i18n.t("toggle_line_comment") })

	map("n", "<leader>rr", function()
		vscode.action("workbench.action.files.copyPathOfActiveFile")
	end, { desc = i18n.t("copy_file_path") })
	map("n", "<leader>rd", function()
		vscode.action("workbench.action.files.copyActiveFileParentFolder")
	end, { desc = i18n.t("copy_folder_path") })
end

return M
