return function()
	require("pure-nvim.utils").load_plugin("catppuccin", {
		integrations = {
			cmp = true,
			dap = true,
			dap_ui = true,
			diffview = true,
			dropbar = true,
			fidget = true,
			flash = true,
			fzf = true,
			gitsigns = true,
			grug_far = true,
			hop = true,
			indent_blankline = true,
			lsp_saga = true,
			lsp_trouble = true,
			markdown = true,
			mason = true,
			mini = true,
			native_lsp = true,
			notify = true,
			nvimtree = true,
			rainbow_delimiters = true,
			render_markdown = true,
			semantic_tokens = true,
			snacks = true,
			treesitter = true,
			treesitter_context = true,
			which_key = true,
		},
	})
end
